// ============================
// 类型目录 — 常量 re-export 层
// 所有常量的实际定义在 src/lib/constants/ 中。
// 此文件仅做 re-export，保持 `import { ... } from '@/types'` 兼容。
// ============================

// 游戏核心机制常量
export {
  ATTRIBUTE_MIN, ATTRIBUTE_MAX, ATTRIBUTE_DEFAULT, ATTRIBUTE_TOTAL_POINTS,
  STRESS_MIN, STRESS_MAX, STRESS_OVERLOAD, STRESS_RECOVERY_BASE, STRESS_RECOVERY_BONUS, STRESS_MODIFIER_MULTIPLIER,
  RELATION_MIN, RELATION_MAX, RELATION_NATURAL_RECOVERY,
  MAX_ITEM_SLOTS,
  MIN_PLAYERS, MAX_PLAYERS, DEFAULT_PLAYERS,
  ALIGNMENT_LAWFUL_LEADERSHIP_BONUS, ALIGNMENT_LAWFUL_DECEPTION_PENALTY,
  ALIGNMENT_CHAOTIC_DECEPTION_BONUS, ALIGNMENT_EVIL_DECEPTION_BONUS, ALIGNMENT_GOOD_AFFINITY_BONUS,
  CHECK_DIFFICULTY_EASY, CHECK_DIFFICULTY_MEDIUM, CHECK_DIFFICULTY_HARD, CHECK_DIFFICULTY_VERY_HARD,
  CHECK_DIFFICULTY_DEFEND, CHECK_DIFFICULTY_JOIN_SUSPECT, CHECK_DIFFICULTY_JOIN_DEFEND,
  CHECK_DIFFICULTY_CALL_VOTE, CHECK_DIFFICULTY_BLOCK_VOTE, CHECK_DIFFICULTY_GUARANTEE, CHECK_DIFFICULTY_EXCLUDE_ALL,
  SILENCE_NEAR_FULL_THRESHOLD,
  DEFAULT_TICK_RATE,
} from '@/lib/constants/game';

// AI 决策阶段权重
export { STAGE_WEIGHT_DUTY, STAGE_WEIGHT_SURVIVAL, STAGE_WEIGHT_INFORMATION, STAGE_WEIGHT_SOCIAL } from '@/lib/constants/scores';

// 狼人概率阈值
export {
  WEREWOLF_PROBABILITY_HIGH,
  WEREWOLF_PROBABILITY_LOW,
  WEREWOLF_PROBABILITY_MEDIUM,
} from '@/lib/constants/belief';

// 身份危机阈值
export {
  IDENTITY_CRISIS_LOW_THRESHOLD,
  IDENTITY_CRISIS_HIGH_THRESHOLD,
  IDENTITY_CRISIS_CRITICAL_THRESHOLD,
} from '@/lib/constants/strategy-thresholds';

// AI 置信度
export { CONFIDENCE_MEDIUM as CONFIDENCE_JOIN_SUSPECT, CONFIDENCE_MEDIUM as CONFIDENCE_JOIN_DEFEND } from '@/lib/constants/mind';

// 关系阈值
export { TRUST_THRESHOLD_MEDIUM as RELATION_FRIENDLY_JOIN_DEFEND } from '@/lib/constants/mind';
