// ========== 心智系统评分常量 ==========

// 意图生成基础分（纯场景描述分数，价值观影响统一由 mindMultiplier 的 valueAlignment 处理）
export const INTENTION_BASE_SCORE_SELF_PRESERVATION = 500;
export const INTENTION_BASE_SCORE_INFORMATION = 200;
export const INTENTION_BASE_SCORE_SOCIAL = 300;
export const INTENTION_BASE_SCORE_ATTACK = 400;
export const INTENTION_BASE_SCORE_PROTECTION = 250;
export const INTENTION_BASE_SCORE_DEFAULT = 100;
export const INTENTION_BASE_SCORE_DEFAULT_OBSERVE = 80;

// ========== 信心值常量 ==========
export const CONFIDENCE_HIGH = 0.8;
export const CONFIDENCE_MEDIUM_HIGH = 0.7;
export const CONFIDENCE_MEDIUM = 0.6;
export const CONFIDENCE_LOW_MEDIUM = 0.5;
export const CONFIDENCE_LOW = 0.4;
export const CONFIDENCE_VERY_LOW = 0.3;

// ========== 心智系统阈值常量 ==========

// 概率阈值
export const PROB_THRESHOLD_HIGH = 0.7;
export const PROB_THRESHOLD_MEDIUM = 0.5;
export const PROB_THRESHOLD_LOW = 0.4;
export const PROB_THRESHOLD_VERY_LOW = 0.3;

// 信息丰富度阈值
export const INFORMATION_RICHNESS_THRESHOLD = 0.5;
export const INFORMATION_RICHNESS_HIGH = 0.8;

// 身份危机阈值
export const CRISIS_THRESHOLD_CRITICAL = 0.7;
export const CRISIS_THRESHOLD_HIGH = 0.5;
export const CRISIS_THRESHOLD_LOW = 0.3;

// 场面紧张度阈值
export const TENSION_THRESHOLD_HIGH = 0.7;

// 信任阈值
export const TRUST_THRESHOLD_HIGH = 5;
export const TRUST_THRESHOLD_MEDIUM = 3;

// 属性阈值
export const ATTRIBUTE_LEADERSHIP_HIGH = 6;

// 攻击次数阈值
export const ATTACK_COUNT_THRESHOLD = 2;

// ========== 心智模拟常量 ==========

// 心智模拟默认分数
export const SIMULATION_DEFAULT_GOAL_ALIGNMENT = 0.5;
export const SIMULATION_DEFAULT_EXPOSURE_RISK = 0.5;

// 心智模拟具体值
export const SIMULATION_EXPOSURE_RISK_HIGH = 0.7;
export const SIMULATION_EXPOSURE_RISK_MEDIUM = 0.6;
export const SIMULATION_EXPOSURE_RISK_LOW = 0.3;
export const SIMULATION_EXPOSURE_RISK_VERY_LOW = 0.2;
export const SIMULATION_GOAL_ALIGNMENT_HIGH = 0.9;
export const SIMULATION_GOAL_ALIGNMENT_MEDIUM = 0.8;
export const SIMULATION_GOAL_ALIGNMENT_LOW = 0.4;
export const SIMULATION_GOAL_ALIGNMENT_VERY_LOW = 0.3;
export const SIMULATION_CONFIDENCE_HIGH = 0.8;
export const SIMULATION_CONFIDENCE_MEDIUM = 0.6;
export const SIMULATION_CONFIDENCE_LOW = 0.5;

// ========== 时机评估常量 ==========

// 时机评估默认分数
export const TIMING_DEFAULT_SCORE = 0.5;

// 时机评估具体值
export const TIMING_URGENCY_HIGH = 0.9;
export const TIMING_URGENCY_MEDIUM = 0.7;
export const TIMING_URGENCY_LOW = 0.4;
export const TIMING_URGENCY_VERY_LOW = 0.3;
export const TIMING_URGENCY_MINIMAL = 0.2;

export const TIMING_CREDIBILITY_HIGH = 0.9;
export const TIMING_CREDIBILITY_MEDIUM = 0.7;
export const TIMING_CREDIBILITY_LOW = 0.5;
export const TIMING_CREDIBILITY_VERY_LOW = 0.4;
export const TIMING_CREDIBILITY_MINIMAL = 0.3;

export const TIMING_RISK_HIGH = 0.8;
export const TIMING_RISK_MEDIUM = 0.6;
export const TIMING_RISK_LOW = 0.5;
export const TIMING_RISK_VERY_LOW = 0.4;
export const TIMING_RISK_MINIMAL = 0.3;

export const TIMING_IMPACT_HIGH = 0.8;
export const TIMING_IMPACT_MEDIUM = 0.7;
export const TIMING_IMPACT_LOW = 0.5;
export const TIMING_IMPACT_VERY_LOW = 0.4;
export const TIMING_IMPACT_MINIMAL = 0.3;

// 时机评估权重
export const TIMING_WEIGHT_URGENCY = 0.3;
export const TIMING_WEIGHT_CREDIBILITY = 0.25;
export const TIMING_WEIGHT_RISK = 0.2;
export const TIMING_WEIGHT_IMPACT = 0.15;
export const TIMING_WEIGHT_OPPORTUNITY_COST = 0.1;

// ========== 社交情境常量 ==========

// 行动强度
export const ACTION_INTENSITY_ACCUSE = 3;
export const ACTION_INTENSITY_SUSPECT = 2;
export const ACTION_INTENSITY_JOIN_SUSPECT = 1.5;
export const ACTION_INTENSITY_DEFEND = 1;
export const ACTION_INTENSITY_CALL_VOTE = 2.5;
export const ACTION_INTENSITY_BLOCK_VOTE = 2;
export const ACTION_INTENSITY_DEFAULT = 0.5;

// 身份危机因子
export const CRISIS_FACTOR_SILENCE_CRITICAL = 1.5;
export const CRISIS_FACTOR_OBSERVE_CRITICAL = 1.3;
export const CRISIS_FACTOR_DEFEND_CRITICAL = 1.4;
export const CRISIS_FACTOR_REBUT_CRITICAL = 1.6;
export const CRISIS_FACTOR_ACCUSE_CRITICAL = 0.5;
export const CRISIS_FACTOR_CALL_VOTE_CRITICAL = 0.4;
export const CRISIS_FACTOR_CLAIM_IDENTITY_CRITICAL = 0.3;
export const CRISIS_FACTOR_DEFAULT_CRITICAL = 1.0;

export const CRISIS_FACTOR_SILENCE_HIGH = 1.3;
export const CRISIS_FACTOR_DEFEND_HIGH = 1.2;
export const CRISIS_FACTOR_ACCUSE_HIGH = 0.7;
export const CRISIS_FACTOR_CALL_VOTE_HIGH = 0.6;
export const CRISIS_FACTOR_DEFAULT_HIGH = 1.0;

// 关系因子
export const RELATION_FACTOR_DEFEND_TRUSTED = 1.4;
export const RELATION_FACTOR_GUARANTEE_TRUSTED = 1.5;
export const RELATION_FACTOR_ACCUSE_TRUSTED = 0.4;
export const RELATION_FACTOR_ACCUSE_SUSPICIOUS = 1.5;
export const RELATION_FACTOR_SUSPECT_SUSPICIOUS = 1.3;
export const RELATION_FACTOR_DEFEND_SUSPICIOUS = 0.3;
export const RELATION_FACTOR_DEFAULT = 1.0;

// 社交情境加成
export const SOCIAL_BONUS_SILENCE_HIGH_TENSION = 0.7;
export const SOCIAL_BONUS_DEFEND_TARGET = 1.3;
export const SOCIAL_BONUS_CALL_VOTE_LEADER = 1.2;
export const SOCIAL_BONUS_OBSERVE_RICH_INFO = 0.8;
export const SOCIAL_BONUS_DEFAULT = 1.0;

// ========== 能力匹配常量 ==========

// 能力匹配因子
export const CAPABILITY_FACTOR_EXCELLENT = 1.3;
export const CAPABILITY_FACTOR_GOOD = 1.1;
export const CAPABILITY_FACTOR_AVERAGE = 1.0;
export const CAPABILITY_FACTOR_POOR = 0.7;
export const CAPABILITY_FACTOR_VERY_POOR = 0.4;

// 能力匹配阈值
export const CAPABILITY_THRESHOLD_EXCELLENT = 0.8;
export const CAPABILITY_THRESHOLD_GOOD = 0.6;
export const CAPABILITY_THRESHOLD_AVERAGE = 0.4;
export const CAPABILITY_THRESHOLD_POOR = 0.3;

// 能力匹配权重
export const CAPABILITY_PRIMARY_WEIGHT = 0.7;
export const CAPABILITY_SECONDARY_WEIGHT = 0.3;

// ========== 乘法系统常量 ==========

export const MIND_MULTIPLIER_BASE = 0.5;
export const MIND_MULTIPLIER_SCALE = 0.5;
export const MIND_MULTIPLIER_SOCIAL_BASE = 0.8;
export const MIND_MULTIPLIER_SOCIAL_SCALE = 0.2;

// ========== 温度系统常量 ==========

export const TEMPERATURE_BASE = 1.0;
export const TEMPERATURE_STRESS_LOW = 0.4;
export const TEMPERATURE_STRESS_HIGH = 0.8;
export const TEMPERATURE_CRISIS_CRITICAL = 0.3;
export const TEMPERATURE_CRISIS_HIGH = 0.15;
export const TEMPERATURE_WEREWOLF = 0.2;
export const TEMPERATURE_LOGIC_SCALE = 0.02;
export const TEMPERATURE_STEALTH_SCALE = 0.02;
export const TEMPERATURE_ANXIOUS = 0.3;
export const TEMPERATURE_CONFIDENT = -0.2;
export const TEMPERATURE_ANGRY = 0.4;
export const TEMPERATURE_MIN = 0.3;
export const TEMPERATURE_MAX = 2.5;

// ========== 价值观系统常量 ==========

export const VALUE_BASE = 0.5;
export const VALUE_SELF_PRESERVATION_BASE = 0.6;
export const VALUE_ATTRIBUTE_SCALE = 0.02;
export const VALUE_ATTRIBUTE_SCALE_LOW = 0.01;
export const VALUE_CLAMP_MIN = 0;
export const VALUE_CLAMP_MAX = 1;

// ========== 命名空间对象：按模块组织常量（推荐新代码使用） ==========

export const MIND = {
  // 意图生成基础分
  INTENTION: {
    BASE_SCORE_SELF_PRESERVATION: INTENTION_BASE_SCORE_SELF_PRESERVATION,
    BASE_SCORE_INFORMATION: INTENTION_BASE_SCORE_INFORMATION,
    BASE_SCORE_SOCIAL: INTENTION_BASE_SCORE_SOCIAL,
    BASE_SCORE_ATTACK: INTENTION_BASE_SCORE_ATTACK,
    BASE_SCORE_PROTECTION: INTENTION_BASE_SCORE_PROTECTION,
    BASE_SCORE_DEFAULT: INTENTION_BASE_SCORE_DEFAULT,
    BASE_SCORE_DEFAULT_OBSERVE: INTENTION_BASE_SCORE_DEFAULT_OBSERVE,
  },

  // 信心值
  CONFIDENCE: {
    HIGH: CONFIDENCE_HIGH,
    MEDIUM_HIGH: CONFIDENCE_MEDIUM_HIGH,
    MEDIUM: CONFIDENCE_MEDIUM,
    LOW_MEDIUM: CONFIDENCE_LOW_MEDIUM,
    LOW: CONFIDENCE_LOW,
    VERY_LOW: CONFIDENCE_VERY_LOW,
  },

  // 阈值
  THRESHOLD: {
    PROB_HIGH: PROB_THRESHOLD_HIGH,
    PROB_MEDIUM: PROB_THRESHOLD_MEDIUM,
    PROB_LOW: PROB_THRESHOLD_LOW,
    PROB_VERY_LOW: PROB_THRESHOLD_VERY_LOW,
    INFO_RICHNESS: INFORMATION_RICHNESS_THRESHOLD,
    INFO_RICHNESS_HIGH: INFORMATION_RICHNESS_HIGH,
    CRISIS_CRITICAL: CRISIS_THRESHOLD_CRITICAL,
    CRISIS_HIGH: CRISIS_THRESHOLD_HIGH,
    CRISIS_LOW: CRISIS_THRESHOLD_LOW,
    TENSION_HIGH: TENSION_THRESHOLD_HIGH,
    TRUST_HIGH: TRUST_THRESHOLD_HIGH,
    TRUST_MEDIUM: TRUST_THRESHOLD_MEDIUM,
    LEADERSHIP_HIGH: ATTRIBUTE_LEADERSHIP_HIGH,
    ATTACK_COUNT: ATTACK_COUNT_THRESHOLD,
  },

  // 心智模拟
  SIMULATION: {
    DEFAULT_GOAL_ALIGNMENT: SIMULATION_DEFAULT_GOAL_ALIGNMENT,
    DEFAULT_EXPOSURE_RISK: SIMULATION_DEFAULT_EXPOSURE_RISK,
    EXPOSURE_RISK_HIGH: SIMULATION_EXPOSURE_RISK_HIGH,
    EXPOSURE_RISK_MEDIUM: SIMULATION_EXPOSURE_RISK_MEDIUM,
    EXPOSURE_RISK_LOW: SIMULATION_EXPOSURE_RISK_LOW,
    EXPOSURE_RISK_VERY_LOW: SIMULATION_EXPOSURE_RISK_VERY_LOW,
    GOAL_ALIGNMENT_HIGH: SIMULATION_GOAL_ALIGNMENT_HIGH,
    GOAL_ALIGNMENT_MEDIUM: SIMULATION_GOAL_ALIGNMENT_MEDIUM,
    GOAL_ALIGNMENT_LOW: SIMULATION_GOAL_ALIGNMENT_LOW,
    GOAL_ALIGNMENT_VERY_LOW: SIMULATION_GOAL_ALIGNMENT_VERY_LOW,
    CONFIDENCE_HIGH: SIMULATION_CONFIDENCE_HIGH,
    CONFIDENCE_MEDIUM: SIMULATION_CONFIDENCE_MEDIUM,
    CONFIDENCE_LOW: SIMULATION_CONFIDENCE_LOW,
  },

  // 时机评估
  TIMING: {
    DEFAULT_SCORE: TIMING_DEFAULT_SCORE,
    URGENCY_HIGH: TIMING_URGENCY_HIGH,
    URGENCY_MEDIUM: TIMING_URGENCY_MEDIUM,
    URGENCY_LOW: TIMING_URGENCY_LOW,
    URGENCY_VERY_LOW: TIMING_URGENCY_VERY_LOW,
    URGENCY_MINIMAL: TIMING_URGENCY_MINIMAL,
    CREDIBILITY_HIGH: TIMING_CREDIBILITY_HIGH,
    CREDIBILITY_MEDIUM: TIMING_CREDIBILITY_MEDIUM,
    CREDIBILITY_LOW: TIMING_CREDIBILITY_LOW,
    CREDIBILITY_VERY_LOW: TIMING_CREDIBILITY_VERY_LOW,
    CREDIBILITY_MINIMAL: TIMING_CREDIBILITY_MINIMAL,
    RISK_HIGH: TIMING_RISK_HIGH,
    RISK_MEDIUM: TIMING_RISK_MEDIUM,
    RISK_LOW: TIMING_RISK_LOW,
    RISK_VERY_LOW: TIMING_RISK_VERY_LOW,
    RISK_MINIMAL: TIMING_RISK_MINIMAL,
    IMPACT_HIGH: TIMING_IMPACT_HIGH,
    IMPACT_MEDIUM: TIMING_IMPACT_MEDIUM,
    IMPACT_LOW: TIMING_IMPACT_LOW,
    IMPACT_VERY_LOW: TIMING_IMPACT_VERY_LOW,
    IMPACT_MINIMAL: TIMING_IMPACT_MINIMAL,
    WEIGHT_URGENCY: TIMING_WEIGHT_URGENCY,
    WEIGHT_CREDIBILITY: TIMING_WEIGHT_CREDIBILITY,
    WEIGHT_RISK: TIMING_WEIGHT_RISK,
    WEIGHT_IMPACT: TIMING_WEIGHT_IMPACT,
    WEIGHT_OPPORTUNITY_COST: TIMING_WEIGHT_OPPORTUNITY_COST,
  },

  // 社交情境
  SOCIAL: {
    ACTION_INTENSITY_ACCUSE: ACTION_INTENSITY_ACCUSE,
    ACTION_INTENSITY_SUSPECT: ACTION_INTENSITY_SUSPECT,
    ACTION_INTENSITY_JOIN_SUSPECT: ACTION_INTENSITY_JOIN_SUSPECT,
    ACTION_INTENSITY_DEFEND: ACTION_INTENSITY_DEFEND,
    ACTION_INTENSITY_CALL_VOTE: ACTION_INTENSITY_CALL_VOTE,
    ACTION_INTENSITY_BLOCK_VOTE: ACTION_INTENSITY_BLOCK_VOTE,
    ACTION_INTENSITY_DEFAULT: ACTION_INTENSITY_DEFAULT,
    CRISIS_FACTOR_SILENCE_CRITICAL: CRISIS_FACTOR_SILENCE_CRITICAL,
    CRISIS_FACTOR_OBSERVE_CRITICAL: CRISIS_FACTOR_OBSERVE_CRITICAL,
    CRISIS_FACTOR_DEFEND_CRITICAL: CRISIS_FACTOR_DEFEND_CRITICAL,
    CRISIS_FACTOR_REBUT_CRITICAL: CRISIS_FACTOR_REBUT_CRITICAL,
    CRISIS_FACTOR_ACCUSE_CRITICAL: CRISIS_FACTOR_ACCUSE_CRITICAL,
    CRISIS_FACTOR_CALL_VOTE_CRITICAL: CRISIS_FACTOR_CALL_VOTE_CRITICAL,
    CRISIS_FACTOR_CLAIM_IDENTITY_CRITICAL: CRISIS_FACTOR_CLAIM_IDENTITY_CRITICAL,
    CRISIS_FACTOR_DEFAULT_CRITICAL: CRISIS_FACTOR_DEFAULT_CRITICAL,
    CRISIS_FACTOR_SILENCE_HIGH: CRISIS_FACTOR_SILENCE_HIGH,
    CRISIS_FACTOR_DEFEND_HIGH: CRISIS_FACTOR_DEFEND_HIGH,
    CRISIS_FACTOR_ACCUSE_HIGH: CRISIS_FACTOR_ACCUSE_HIGH,
    CRISIS_FACTOR_CALL_VOTE_HIGH: CRISIS_FACTOR_CALL_VOTE_HIGH,
    CRISIS_FACTOR_DEFAULT_HIGH: CRISIS_FACTOR_DEFAULT_HIGH,
    RELATION_FACTOR_DEFEND_TRUSTED: RELATION_FACTOR_DEFEND_TRUSTED,
    RELATION_FACTOR_GUARANTEE_TRUSTED: RELATION_FACTOR_GUARANTEE_TRUSTED,
    RELATION_FACTOR_ACCUSE_TRUSTED: RELATION_FACTOR_ACCUSE_TRUSTED,
    RELATION_FACTOR_ACCUSE_SUSPICIOUS: RELATION_FACTOR_ACCUSE_SUSPICIOUS,
    RELATION_FACTOR_SUSPECT_SUSPICIOUS: RELATION_FACTOR_SUSPECT_SUSPICIOUS,
    RELATION_FACTOR_DEFEND_SUSPICIOUS: RELATION_FACTOR_DEFEND_SUSPICIOUS,
    RELATION_FACTOR_DEFAULT: RELATION_FACTOR_DEFAULT,
    BONUS_SILENCE_HIGH_TENSION: SOCIAL_BONUS_SILENCE_HIGH_TENSION,
    BONUS_DEFEND_TARGET: SOCIAL_BONUS_DEFEND_TARGET,
    BONUS_CALL_VOTE_LEADER: SOCIAL_BONUS_CALL_VOTE_LEADER,
    BONUS_OBSERVE_RICH_INFO: SOCIAL_BONUS_OBSERVE_RICH_INFO,
    BONUS_DEFAULT: SOCIAL_BONUS_DEFAULT,
  },

  // 能力匹配
  CAPABILITY: {
    FACTOR_EXCELLENT: CAPABILITY_FACTOR_EXCELLENT,
    FACTOR_GOOD: CAPABILITY_FACTOR_GOOD,
    FACTOR_AVERAGE: CAPABILITY_FACTOR_AVERAGE,
    FACTOR_POOR: CAPABILITY_FACTOR_POOR,
    FACTOR_VERY_POOR: CAPABILITY_FACTOR_VERY_POOR,
    THRESHOLD_EXCELLENT: CAPABILITY_THRESHOLD_EXCELLENT,
    THRESHOLD_GOOD: CAPABILITY_THRESHOLD_GOOD,
    THRESHOLD_AVERAGE: CAPABILITY_THRESHOLD_AVERAGE,
    THRESHOLD_POOR: CAPABILITY_THRESHOLD_POOR,
    PRIMARY_WEIGHT: CAPABILITY_PRIMARY_WEIGHT,
    SECONDARY_WEIGHT: CAPABILITY_SECONDARY_WEIGHT,
  },

  // 乘法系统
  MULTIPLIER: {
    BASE: MIND_MULTIPLIER_BASE,
    SCALE: MIND_MULTIPLIER_SCALE,
    SOCIAL_BASE: MIND_MULTIPLIER_SOCIAL_BASE,
    SOCIAL_SCALE: MIND_MULTIPLIER_SOCIAL_SCALE,
  },

  // 温度系统
  TEMPERATURE: {
    BASE: TEMPERATURE_BASE,
    STRESS_LOW: TEMPERATURE_STRESS_LOW,
    STRESS_HIGH: TEMPERATURE_STRESS_HIGH,
    CRISIS_CRITICAL: TEMPERATURE_CRISIS_CRITICAL,
    CRISIS_HIGH: TEMPERATURE_CRISIS_HIGH,
    WEREWOLF: TEMPERATURE_WEREWOLF,
    LOGIC_SCALE: TEMPERATURE_LOGIC_SCALE,
    STEALTH_SCALE: TEMPERATURE_STEALTH_SCALE,
    ANXIOUS: TEMPERATURE_ANXIOUS,
    CONFIDENT: TEMPERATURE_CONFIDENT,
    ANGRY: TEMPERATURE_ANGRY,
    MIN: TEMPERATURE_MIN,
    MAX: TEMPERATURE_MAX,
  },

  // 价值观系统
  VALUE: {
    BASE: VALUE_BASE,
    SELF_PRESERVATION_BASE: VALUE_SELF_PRESERVATION_BASE,
    ATTRIBUTE_SCALE: VALUE_ATTRIBUTE_SCALE,
    ATTRIBUTE_SCALE_LOW: VALUE_ATTRIBUTE_SCALE_LOW,
    CLAMP_MIN: VALUE_CLAMP_MIN,
    CLAMP_MAX: VALUE_CLAMP_MAX,
  },
} as const;
